from typing import Dict
from pix2tex.cli import LatexOCR 
from pix2text import Pix2Text
class ORChelper:
    """
    A helper class to use Pix2Text and LatexOCR.
    """

    latex_model = LatexOCR()
    doc_model = Pix2Text()


    def combine(self, latex_img, doc_img):
        
        latex = self.latex_model(latex_img)
        raw_doc = self.doc_model(doc_img)
        parsed_doc = ORChelper.parse_doc(raw_doc)
        return f"{latex} \n {parsed_doc}"
        
    @staticmethod
    def parse_doc(raw_doc: Dict) -> str:
        """
        Parses a raw document generated by Pix2Text into a list of sentences.

        Parameter
        --------- 
        raw_doc : Dict 
            The output dictionary from Pix2Text to be parsed.

        Returns
        -------
        parsed : str
            A string of sentences.
        """
        parsed = []
        line_number = 0
        temp = ""
        for output in raw_doc:
            if output['type'] == 'text':
                if output['line_number'] == line_number:
                    temp += " " + output['text']
                else:
                    parsed.append(temp)
                    temp = output['text']
                    line_number += 1
        parsed.append(temp)
        return ' \n '.join(parsed)



